// pages/u/settings/index.vue
<template>
  <div id="users-settings" class="section column is-9 container">
    <div class="columns">
      <div class="column bg-white pd-15rem radius-box">
        <div class="columns">
          <div class="column is-6">
            <div class="setting-header">
              <h2 class="title is-4 sp-font weight-700">You</h2>
            </div>

            <div class="form-body">
              <div class="field">
                <label class="label sp-font">Name</label>
                <div class="control">
                  <input
                    v-model="userSettings.customName"
                    class="input"
                    type="text"
                    placeholder="Your Name"
                  />
                </div>
              </div>

              <div class="field">
                <label class="label sp-font">Tagline</label>
                <div class="control">
                  <input
                    v-model="userSettings.tagline"
                    class="input"
                    type="text"
                    placeholder="Your tagline"
                  />
                </div>
              </div>

              <div class="field">
                <label class="label sp-font">Website</label>
                <div class="control">
                  <input
                    v-model="userSettings.website"
                    class="input"
                    type="url"
                    placeholder="https://askmakers.co"
                  />
                </div>
              </div>

              <label class="label sp-font">Profile Picture</label>
              <img
                v-if="imageData"
                :src="imageData"
                width="60px"
                class="is-rounded"
              />
              <div class="field file is-boxed">
                <label class="file-label">
                  <input
                    class="file-input"
                    type="file"
                    name="picture"
                    @change="onFileChange($event)"
                  />
                  <span class="file-cta">
                    <span class="file-icon">
                      <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                      Choose a file…
                    </span>
                  </span>
                </label>
              </div>

              <div class="field">
                <label class="label sp-font">Emeil Notification</label>
                <label class="checkbox">
                  <input
                    v-model="userSettings.isEmailNewQuestionNotification"
                    type="checkbox"
                  />
                  Send email when you get a new 1on1 question
                </label>
              </div>
              <div class="field">
                <label class="checkbox">
                  <input
                    v-model="
                      userSecretSettings.isEmailNewGeneralQuestionNotification
                    "
                    type="checkbox"
                  />
                  Send email when you get a new question
                </label>
              </div>
            </div>
          </div>
          <div class="column is-6">
            <div class="setting-header">
              <h2 class="title is-4 sp-font weight-700">Social</h2>
            </div>
            <div class="form-body">
              <div class="field social-from">
                <div class="label sp-font">Twitter Handle</div>
                <div class="field-body">
                  <div class="field is-expanded">
                    <div class="field has-addons">
                      <p class="control">
                        <a class="button is-static">
                          <i class="fab fa-twitter"></i>
                        </a>
                      </p>
                      <p class="control is-expanded">
                        <input
                          v-model="userSettings.social.twitter"
                          class="input"
                          type="text"
                          placeholder="jack"
                        />
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div class="field social-from">
                <div class="label sp-font">Product Hunt Handle</div>
                <div class="field-body">
                  <div class="field is-expanded">
                    <div class="field has-addons">
                      <p class="control">
                        <a class="button is-static">
                          <i class="fab fa-product-hunt"></i>
                        </a>
                      </p>
                      <p class="control is-expanded">
                        <input
                          v-model="userSettings.social.productHunt"
                          class="input"
                          type="text"
                          placeholder="rrhoover"
                        />
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div class="field social-from">
                <div class="label sp-font">GitHub Handle</div>
                <div class="field-body">
                  <div class="field is-expanded">
                    <div class="field has-addons">
                      <p class="control">
                        <a class="button is-static">
                          <i class="fab fa-github"></i>
                        </a>
                      </p>
                      <p class="control is-expanded">
                        <input
                          v-model="userSettings.social.gitHub"
                          class="input"
                          type="text"
                          placeholder="defunkt"
                        />
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div class="field social-from">
                <div class="label sp-font">Patreon Handle</div>
                <div class="field-body">
                  <div class="field is-expanded">
                    <div class="field has-addons">
                      <p class="control">
                        <a class="button is-static">
                          <i class="fab fa-patreon"></i>
                        </a>
                      </p>
                      <p class="control is-expanded">
                        <input
                          v-model="userSettings.social.patreon"
                          class="input"
                          type="text"
                          placeholder="jackconte"
                        />
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="columns">
          <div class="column">
            <div class="is-divider"></div>
          </div>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control">
              <button
                v-if="isLoading"
                class="button is-primary is-loading is-medium is-rounded"
                disabled
              >
                Save
              </button>
              <button
                v-else
                class="button is-medium is-primary is-rounded"
                @click.prevent="update"
              >
                Save
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import updateDoc from '~/plugins/updateDoc'
import firebase from '~/plugins/firebase'
// Use firestore
import 'firebase/firestore'
const firestore = firebase.firestore()

export default {
  data() {
    return {
      imageData: '',
      isLoading: false,
      userSettings: {
        customName: '',
        tagline: '',
        website: '',
        picture: '',
        social: {
          twitter: '',
          productHunt: '',
          gitHub: '',
          patreon: ''
        }
      },
      userSecretSettings: {
        isEmailNewGeneralQuestionNotification: true
      }
    }
  },
  head() {
    return {
      meta: [{ hid: 'robots', name: 'robots', content: 'noindex' }]
    }
  },
  validate({ store }) {
    if (store.getters.getLoginStatus === true) {
      return true
    }
    return false
  },
  async created() {
    this.userSettings = this.$store.getters.getUserInfo
    const secretUserData = await firestore
      .collection('secretUsers')
      .doc(this.$store.getters.getUserInfo.uid)
      .get()
    /**
     * メール受け取り設定(isEmailNewGeneralQuestionNotification)はsecretUserコレクションに格納されているのでここで取得
     **/
    const secretUser = secretUserData.data()
    this.userSecretSettings.isEmailNewGeneralQuestionNotification =
      secretUser.isEmailNewGeneralQuestionNotification
  },
  methods: {
    async update() {
      this.isLoading = true
      try {
        if (this.imageData !== '') {
          this.userSettings.picture = await this.upload(
            this.$store.getters.getUserInfo.uid
          )
        }
        const userRef = firestore
          .collection('publicUsers')
          .doc(this.$store.getters.getUserInfo.uid)
        const userSecretRef = firestore
          .collection('secretUsers')
          .doc(this.$store.getters.getUserInfo.uid)
        await Promise.all([
          updateDoc(userRef, this.userSettings),
          updateDoc(userSecretRef, this.userSecretSettings)
        ])
        this.$snackbar.open({
          message: 'Successfuly saved',
          type: 'is-success',
          position: 'is-top',
          duration: 3000
        })
      } catch (err) {
        this.$snackbar.open({
          message: 'Something went wrong...Please try again',
          type: 'is-danger',
          position: 'is-top',
          duration: 4000
        })
      } finally {
        this.isLoading = false
      }
    },
    onFileChange(e) {
      this.imageData = ''
      const files = e.target.files
      // blob形式に変換
      this.blob = new Blob(files, { type: 'image/png' })
      if (files.length > 0) {
        const file = files[0]
        const reader = new FileReader()
        reader.onload = (e) => {
          this.imageData = e.target.result
        }
        reader.readAsDataURL(file)
      }
    },
    async upload(id) {
      const updateDataConst = {}
      // 画像処理
      if (this.blob !== null) {
        const storageRef = firebase.storage().ref()
        const uploadRef = storageRef.child(`users/${id}.png`)
        await uploadRef.put(this.blob)
        const url = await uploadRef.getDownloadURL()
        updateDataConst.picture = url
        this.downloadURL = url
        return url
      }
    }
  }
}
</script>

<style lang="scss" scoped>
$thinBorder: 1px solid #e8e0e0 !important;
.setting-header {
  border-bottom: $thinBorder;
  padding-bottom: 0.75rem;
}

.social-from {
  width: 300px;
}

.form-body {
  margin-top: 1rem;
}

#users-settings {
  .is-divider {
    margin: 0;
    border-top: 1px solid #dbdbdb;
  }
}
</style>

// pages/settings.tsx
import React from 'react'
import Head from 'next/head'
import { useSelector, useDispatch } from 'react-redux'
import { loginUser as loginUserAction } from '../store/action'
import Layout from '../components/Layout'
import Input from '../components/Input'
import Upload from '../components/Upload'
import getBase64 from '../plugins/getBase64'
import uploadToStorage from '../plugins/uploadToStorage'
import { message } from 'antd'
// import uuid from 'uuid/v4'
import firebase from '../plugins/firebase'
import 'firebase/firestore'
import 'firebase/storage'

const db = firebase.firestore()

const Settings = () => {
  const loginUser = useSelector(state => state.loginUser)
  const dispatch = useDispatch()

  const [tagline, setTagline] = React.useState('')
  const [twitter, setTwitter] = React.useState('')
  const [producthunt, setProducthunt] = React.useState('')
  const [github, setGithub] = React.useState('')
  const [patreon, setPatreon] = React.useState('')
  const [imageUrl, setImageUrl] = React.useState('')
  const [isSaving, setIsSaving] = React.useState(false)
  const [name, setName] = React.useState('')
  const [website, setWebsite] = React.useState('')
  const [isLoadingImage, setIsLoadingImage] = React.useState(false)

  React.useEffect(() => {
    setName(loginUser.customName)
    if (loginUser.tagline !== undefined) {
      setTagline(loginUser.tagline)
    }
    if (loginUser.website !== undefined) {
      setWebsite(loginUser.website)
    }
    if (loginUser.social !== undefined && loginUser.social.twitter !== undefined) {
      setTwitter(loginUser.social.twitter)
    }
    if (loginUser.social !== undefined && loginUser.social.productHunt !== undefined) {
      setProducthunt(loginUser.social.productHunt)
    }
    if (loginUser.social !== undefined && loginUser.social.gitHub !== undefined) {
      setGithub(loginUser.social.gitHub)
    }
    if (loginUser.social !== undefined && loginUser.social.patreon !== undefined) {
      setPatreon(loginUser.social.patreon)
    }
  }, [loginUser])

  const handleSubmit = async e => {
    e.preventDefault()
    setIsSaving(true)
    try {
      const updateData: IUpdateData = {}

      if (name === '') {
        message.error('Please put your name')
        return
      }

      updateData.customName = name

      // Pictureのみここで設定
      if (loginUser.picture !== undefined) {
        updateData.picture = loginUser.picture
      }

      let pictureImage = ''
      if (imageUrl !== '') {
        // const id = uuid().split('-').join('')
        pictureImage = await uploadToStorage(loginUser.uid, imageUrl, firebase)
        updateData.picture = pictureImage
      }
      updateData.tagline = tagline
      updateData.website = website
      updateData.social = {}
      updateData.social.twitter = twitter
      updateData.social.productHunt = producthunt
      updateData.social.gitHub = github
      updateData.social.patreon = patreon
      updateData.username = loginUser.username
      updateData.uid = loginUser.uid
      await db
        .collection('publicUsers')
        .doc(loginUser.uid)
        .update(updateData)
      message.success('Updated successfully')
      dispatch(loginUserAction(updateData))
    } catch (err) {
      console.log('err!!!')
      console.error(err)
      message.error('An error occured. Please try again.')
    } finally {
      setIsSaving(false)
    }
  }

  const handleChangeImage = info => {
    if (info.file.status === 'uploading') {
      setIsLoadingImage(true)
      return
    }
    if (info.file.status === 'done') {
      // Get this url from response in real world.
      getBase64(info.file.originFileObj, imageUrl => {
        setImageUrl(imageUrl)
        setIsLoadingImage(false)
      })
    }
  }
  const title = 'Settings | AskMakers - Ask experienced makers questions'

  return (
    <>
    <Head>
      <meta key="robots" name="robots" content="noindex" />
      <title key="title">{title}</title>
      <meta
        key="og:title"
        property="og:title"
        content={title}
      />
      <meta key="og:site_name" property="og:site_name" content={title} />
    </Head>
    <Layout>
      <div className="w-full md:w-9/12 lg:w-9/12 my-10 m-auto p-2">
        <h1 className="text-4xl font-bold mb-8">
          Settings
        </h1>
        <form onSubmit={handleSubmit}>
          <div className="flex flex-wrap justify-between -mx-3">
            <div className="w-full md:w-6/12 lg:w-6/12 px-3">
              <div className="mb-3">
                <Input label="Name" id="name" type="text" value={name} handleChange={e => setName(e.target.value)} />
              </div>
              <div className="mb-3">
                <Input label="Tagline" id="tagline" type="text" value={tagline} handleChange={e => setTagline(e.target.value)}/>
              </div>
              <div className="mb-3">
                <Input label="Website" placeholder="https://askmakers.co" id="website" type="url" value={website} handleChange={e => setWebsite(e.target.value)}/>
              </div>
              <div className="mb-3 md:mb-0 lg:mb-0">
                <Upload label="Profile Picture" imageUrl={imageUrl} handleChange={handleChangeImage} isLoading={isLoadingImage} />
              </div>
            </div>
            <div className="w-full md:w-6/12 lg:w-6/12 px-3">
              <div className="mb-3">
                <Input label="Twitter Handle" placeholder="jack" id="twitter" type="text" value={twitter} handleChange={e => setTwitter(e.target.value)} />
              </div>
              <div className="mb-3">
                <Input label="Product Hunt Handle" placeholder="rrhoover" id="producthunt" type="text" value={producthunt} handleChange={e => setProducthunt(e.target.value)} />
              </div>
              <div className="mb-3">
                <Input label="GitHub Handle" placeholder="defunkt" id="github" type="text" value={github} handleChange={e => setGithub(e.target.value)} />
              </div>
              <Input label="Patreon Handle" placeholder="jackconte" id="patreon" type="text" value={patreon} handleChange={e => setPatreon(e.target.value)} />
            </div>
          </div>
          <div className="px-2 md:px-0 lg:px-0">
            {isSaving ?
              <button
                disabled
                className="rounded px-6 py-3 bg-gray-500 text-white font-semibold mt-4 cursor-not-allowed focus:outline-none"
              >
                Submitting…
              </button>
              :
              <button
                type="submit"
                className="rounded px-6 py-3 bg-gray-900 text-white font-semibold mt-4 focus:outline-none"
              >
                Update
              </button>
            }
          </div>
        </form>
      </div>
    </Layout>
    </>
  )
}

interface IUpdateData {
  customName?: string
  picture?: string
  tagline?: string
  website?: string
  username?: string
  uid?: string
  social?: ISocial
}

interface ISocial {
  twitter?: string,
  productHunt?: string,
  gitHub?: string,
  patreon?: string
}

export default Settings
